Controllers/DisputasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RpgMvc.Models;

namespace RpgMvc.Controllers
{
    public class DisputasController : Controller
    {
        public string uriBase = "http://leomiguel.somee.com/RpgApi/Disputas/";

        [HttpGet]
        public async Task<ActionResult> IndexAsync()
        {
            try
            {
                if(string.IsNullOrEmpty(HttpContext.Session.GetString("SessionIdUsuario")))
                {
                    return RedirectToAction("Sair", "Usuarios");
                }
                
                HttpClient httpClient = new HttpClient();
                string token = HttpContext.Session.GetString("SessionTokenUsuario");
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                string uriBuscaPersonagens = "http://leomiguel.somee.com/RpgApi/Personagens/GetAll";
                HttpResponseMessage response = await httpClient.GetAsync(uriBuscaPersonagens);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    List<PersonagemViewModel> listaPersonagens = await Task.Run(() =>
                        JsonConvert.DeserializeObject<List<PersonagemViewModel>>(serialized));

                    ViewBag.ListaAtacantes = listaPersonagens;
                    ViewBag.ListaOponentes = listaPersonagens;
                    return View();
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<ActionResult> IndexAsync(DisputaViewModel disputa)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                string uriComplementar = "Arma";

                var content = new StringContent(JsonConvert.SerializeObject(disputa));
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                HttpResponseMessage response = await httpClient.PostAsync(uriBase + uriComplementar, content);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    disputa = await Task.Run(() => JsonConvert.DeserializeObject<DisputaViewModel>(serialized));
                    TempData["Mensagem"] = disputa.Narracao;
                    return RedirectToAction("Index", "Personagens");
                }
                else
                    throw new SystemException(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<ActionResult> IndexHabilidadesAsync()
        {
            try
            {
                if(string.IsNullOrEmpty(HttpContext.Session.GetString("SessionIdUsuario")))
                {
                    return RedirectToAction("Sair", "Usuarios");
                }

                HttpClient httpClient = new HttpClient();
                string token = HttpContext.Session.GetString("SessionTokenUsuario");
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                string uriBuscaPersonagens = "http://leomiguel.somee.com/RpgApi/Personagens/GetAll";
                HttpResponseMessage response = await httpClient.GetAsync(uriBuscaPersonagens);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    List<PersonagemViewModel> listaPersonagens = await Task.Run(() =>
                        JsonConvert.DeserializeObject<List<PersonagemViewModel>>(serialized));

                    ViewBag.ListaAtacantes = listaPersonagens;
                    ViewBag.ListaOponentes = listaPersonagens;
                }
                else
                    throw new System.Exception(serialized);

                string uriBuscaHabilidades = "http://leomiguel.somee.com/RpgApi/PersonagemHabilidades/GetHabilidades";
                response = await httpClient.GetAsync(uriBuscaHabilidades);
                serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    List<HabilidadeViewModel> listaHabilidades = await Task.Run(() =>
                        JsonConvert.DeserializeObject<List<HabilidadeViewModel>>(serialized));
                    ViewBag.ListaHabilidades = listaHabilidades;
                }
                else
                    throw new System.Exception(serialized);

                return View("IndexHabilidades");
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<ActionResult> IndexHabilidadesAsync(DisputaViewModel disputa)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                string uriComplementar = "Habilidade";
                var content = new StringContent(JsonConvert.SerializeObject(disputa));
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                HttpResponseMessage response = await httpClient.PostAsync(uriBase + uriComplementar, content);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    disputa = await Task.Run(() =>
                        JsonConvert.DeserializeObject<DisputaViewModel>(serialized));
                    TempData["Mensagem"] = disputa.Narracao;
                    return RedirectToAction("Index", "Personagens");
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<ActionResult> DisputaGeralAsync()
        {
            try
            {
                if(string.IsNullOrEmpty(HttpContext.Session.GetString("SessionIdUsuario")))
                {
                    return RedirectToAction("Sair", "Usuarios");
                }

                HttpClient httpClient = new HttpClient();

                string token = HttpContext.Session.GetString("SessionTokenUsuario");
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                string uriBuscaPersonagens = "http://leomiguel.somee.com/RpgApi/Personagens/GetAll";
                HttpResponseMessage response = await httpClient.GetAsync(uriBuscaPersonagens);

                string serialized = await response.Content.ReadAsStringAsync();

                List<PersonagemViewModel> listaPersonagens = await Task.Run(() =>
                    JsonConvert.DeserializeObject<List<PersonagemViewModel>>(serialized));

                string uriDisputa = "http://leomiguel.somee.com/RpgApi/Disputas/DisputaEmGrupo";
                DisputaViewModel disputa = new DisputaViewModel();
                disputa.ListaIdPersonagens = new List<int>();
                disputa.ListaIdPersonagens.AddRange(listaPersonagens.Select(p => p.Id));

                var content = new StringContent(JsonConvert.SerializeObject(disputa));
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                response = await httpClient.PostAsync(uriDisputa, content);

                serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    disputa = await Task.Run(() => JsonConvert.DeserializeObject<DisputaViewModel>(serialized));
                    TempData["Mensagem"] = string.Join("<br/>", disputa.Resultados);

                }
                else
                    throw new System.Exception(serialized);

                return RedirectToAction("Index", "Personagens");
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index", "Personagens");
            }
        }

        [HttpGet]
        public async Task<ActionResult> IndexDisputasAsync()
        {
            try
            {
                if(string.IsNullOrEmpty(HttpContext.Session.GetString("SessionIdUsuario")))
                {
                    return RedirectToAction("Sair", "Usuarios");
                }

                string uriComplementar = "Listar";
                HttpClient httpClient = new HttpClient();
                string token = HttpContext.Session.GetString("SessionTokenUsuario");
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                HttpResponseMessage response = await httpClient.GetAsync(uriBase + uriComplementar);
                string serialized = await response.Content.ReadAsStringAsync();

Controllers/PersonagemHabilidadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RpgMvc.Models;
using Newtonsoft.Json;

namespace RpgMvc.Controllers
{
    public class PersonagemHabilidadesController : Controller
    {
        public string uriBase = "http://leomiguel.somee.com/RpgApi/PersonagemHabilidades/";

        [HttpGet("PersonagemHabilidades/{id}")]
        public async Task<ActionResult> IndexAsync(int id)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                string token = HttpContext.Session.GetString("SessionTokenUsuario");
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                HttpResponseMessage response = await httpClient.GetAsync(uriBase + id.ToString());
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    List<PersonagemHabilidadeViewModel> lista = await Task.Run(() =>
                        JsonConvert.DeserializeObject<List<PersonagemHabilidadeViewModel>>(serialized));

                    return View(lista);
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpGet("Delete/{habilidadeId}/{personagemId}")]
        public async Task<ActionResult> DeleteAsync(int habilidadeId, int personagemId)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                string uriComplementar = "DeletePersonagemHabilidade";
                string token = HttpContext.Session.GetString("SessionTokenUsuario");
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                PersonagemHabilidadeViewModel ph = new PersonagemHabilidadeViewModel();
                ph.HabilidadeId = habilidadeId;
                ph.PersonagemId = personagemId;

                var content = new StringContent(JsonConvert.SerializeObject(ph));
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                HttpResponseMessage response = await httpClient.PostAsync(uriBase + uriComplementar, content);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    TempData["Mensagem"] = "Habilidade removida com sucesso";
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
            }
            return RedirectToAction("Index", new { Id = personagemId });
        }

        [HttpGet]
        public async Task<ActionResult> CreateAsync(int id, string nome)
        {
            try
            {
                if(string.IsNullOrEmpty(HttpContext.Session.GetString("SessionIdUsuario")))
                {
                    return RedirectToAction("Sair", "Usuarios");
                }
                
                string uriComplementar = "GetHabilidades";
                HttpClient httpClient = new HttpClient();
                string token = HttpContext.Session.GetString("SessionTokenUsuario");
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                HttpResponseMessage response = await httpClient.GetAsync(uriBase + uriComplementar);

                string serialized = await response.Content.ReadAsStringAsync();
                List<HabilidadeViewModel> habilidades = await Task.Run(() =>
                    JsonConvert.DeserializeObject<List<HabilidadeViewModel>>(serialized));
                ViewBag.ListaHabilidades = habilidades;

                PersonagemHabilidadeViewModel ph = new PersonagemHabilidadeViewModel();
                ph.Personagem = new PersonagemViewModel();
                ph.Habilidade = new HabilidadeViewModel();
                ph.PersonagemId = id;
                ph.Personagem.Nome = nome;

                return View(ph);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Create", new { id, nome });
            }
        }

        [HttpPost]
        public async Task<ActionResult> CreateAsync(PersonagemHabilidadeViewModel ph)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                string token = HttpContext.Session.GetString("SessionTokenUsuario");
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                var content = new StringContent(JsonConvert.SerializeObject(ph));
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                HttpResponseMessage response = await httpClient.PostAsync(uriBase, content);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    TempData["Mensagem"] = "Habilidade cadastrada com sucesso";
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
            }
            return RedirectToAction("Index", new { id = ph.PersonagemId });
        }
    }
}

Views/Personagens/Create.cshtml
@model RpgMvc.Models.PersonagemViewModel
@{
    ViewBag.Title = "Novo Personagem";
}
<h2>Criar um Novo Personagem</h2>
@if (@TempData["Mensagem"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Mensagem"]</div>
}
<!--Configuração para exibir mensagem de erro -->
@if (@TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["MensagemErro"]</div>
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr/>
        <div class="form-group">
            <label class="control-label col-md-2">Nome:</label>
            <div class="col-md-6">
                 @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Pontos de vida:</label>
            <div class="col-md-6">
                 @Html.EditorFor(model => model.PontosVida, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Força:</label>
            <div class="col-md-6">
                 @Html.EditorFor(model => model.Forca, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Inteligência:</label>            
            <div class="col-md-6">
                 @Html.EditorFor(model => model.Inteligencia, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Defesa:</label>
            <div class="col-md-6">
                 @Html.EditorFor(model => model.Defesa, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group"></div>
            <label class="control-label col-md-2">Classe:</label>
            <div class="col-md-6">
                 @Html.DropDownListFor(model => model.Classe, Html.GetEnumSelectList(typeof(RpgMvc.Models.Enuns.ClasseEnum)),
                    "---Selecione---", new { @class = "form-control" })
            </div>
        </div>
        <br>
        <div class="form-group">
             <div class="col-md-offset-2 col-md-6" >
                <input type="submit" value="Salvar" class="btn btn-primary"/>
             </div>
        </div>
}
<div>
    @Html.ActionLink("Retornar", "Index")
</div>

Views/Personagens/Details.cshtml
@model RpgMvc.Models.PersonagemViewModel
@{
    ViewBag.Title = "Detalhes do Personagem";
}
<h2>Detalhes do Personagem</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Id)</dt>
        <dd>@Html.DisplayFor(model => model.Id)</dd>

        <dt>@Html.DisplayNameFor(model => model.Nome)</dt>
        <dd>@Html.DisplayFor(model => model.Nome)</dd>

        <dt>@Html.DisplayNameFor(model => model.PontosVida)</dt>
        <dd>@Html.DisplayFor(model => model.PontosVida)</dd>

        <dt>@Html.DisplayNameFor(model => model.Forca)</dt>
        <dd>@Html.DisplayFor(model => model.Forca)</dd>

        <dt>@Html.DisplayNameFor(model => model.Inteligencia)</dt>
        <dd>@Html.DisplayFor(model => model.Inteligencia)</dd>

        <dt>@Html.DisplayNameFor(model => model.Defesa)</dt>
        <dd>@Html.DisplayFor(model => model.Defesa)</dd>

        <dt>@Html.DisplayNameFor(model => model.Classe)</dt>
        <dd>@Html.DisplayFor(model => model.Classe)</dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new {ìd = Model.Id}) | 
    @Html.ActionLink("Retornar", "Index")
</p>

Views/Personagens/Edit.cshtml
@model RpgMvc.Models.PersonagemViewModel
@{
    ViewBag.Title = "Editar Personagem";
}
<h2>Editar dados do Personagem</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "formcontrol", @readonly = "readonly" } })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Nome:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Pontos de vida:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.PontosVida, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Força:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.Forca, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Inteligência:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.Inteligencia, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Defesa:</label>
            <div class="col-md-6">
                @Html.EditorFor(model => model.Defesa, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Classe:</label>
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.Classe, Html.GetEnumSelectList(typeof(RpgMvc.Models.Enuns.ClasseEnum)),
                         "---Selecione---", new { @class = "form-control" })
            </div>
        </div>
        <br>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Salvar alterações" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Retornar", "Index")
</div>

Views/Personagens/Index.cshtml
<!--Namespace da classe de Modelo para esta view-->
@model IEnumerable<RpgMvc.Models.PersonagemViewModel>
<!--Inclua os TempData para Sucesso e Erro aqui, conforme exemplo na view de Autenticação-->
@{
    ViewBag.Title = "Personagens";
}<!--Título da página para o navegador-->
<h2>Relação de Personagens</h2><!--Título da página-->

@if (@TempData["Mensagem"] != null)
{
    <div class="alert alert-success" role="alert">
        @Html.Raw(TempData["Mensagem"])</div>
}
<!--Configuração para exibir mensagem de erro -->
@if (@TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["MensagemErro"]</div>
}

<p> <!--Links apontando para views na mesma pasta-->
    @Html.ActionLink("Criar Novo Personagem", "Create")
</p>
<table class="table">
    <tr><!--Títulos das colunas da tabela-->
        <th>@Html.DisplayNameFor(model => model.Id)</th>
        <th>@Html.DisplayNameFor(model => model.Nome)</th>
        <th>@Html.DisplayNameFor(model => model.Classe)</th>
        <th>@Html.DisplayNameFor(model => model.PontosVida)</th>
        <th>@Html.DisplayNameFor(model => model.Disputas)</th>
        <th>@Html.DisplayNameFor(model => model.Vitorias)</th>
        <th>@Html.DisplayNameFor(model => model.Derrotas)</th>
        <th></th>
    </tr>
    <!--Looping para escrever os dados na tabela-->
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Id)</td>
            <td>@Html.DisplayFor(modelItem => item.Nome)</td>
            <td>@Html.DisplayFor(modelItem => item.Classe)</td>
            <td>@Html.DisplayFor(modelItem => item.PontosVida)</td>
            <td>@Html.DisplayFor(modelItem => item.Disputas)</td>
            <td>@Html.DisplayFor(modelItem => item.Vitorias)</td>
            <td>@Html.DisplayFor(modelItem => item.Derrotas)</td>
            <td><!--Coluna para Links/botões-->
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
                @Html.ActionLink("Deletar", "Delete", new { id = item.Id }
                        , new { onclick = "return confirm('Deseja realmente deletar este personagem ?');" }) |
                @Html.ActionLink("Listar Habilidades", "Index", "PersonagemHabilidades", new {id = item.Id }) | 
                @Html.ActionLink("Atribuir Habilidade", "Create", "PersonagemHabilidades", new {id = item.Id, nome = item.Nome }) |
                @Html.ActionLink("Restaurar Vida", "RestaurarPontosVida", new { id = item.Id }
                        , new { onclick = "return confirm('Deseja realmente restaurar vida ?');"}) |
                @Html.ActionLink("Zerar Ranking", "ZerarRanking", new { id = item.Id }
                        , new { onclick = "return confirm('Deseja realmente zerar ranking ?');"})
            </td>
        </tr>
    }
</table>
@Html.ActionLink("Embate com armas!", "Index", "Disputas",
    null, new { @class = "btn btn-warning" })
@Html.ActionLink("Embate com habilidades!", "IndexHabilidades", "Disputas",
    null, new { @class = "btn btn-dark" })
@Html.ActionLink("Embate em grupo!", "DisputaGeral", "Disputas",
    null, new { @class = "btn btn-danger" })
@Html.ActionLink("Resetar ranking e Restaurar vida!", "ZerarRankingRestaurarVidas", "Personagens",
    null, new { @class = "btn btn-secondary", onclick = "return confim('Deseja realmente realizar esta ação ?');" })